### ISSUE TITLE
Error in terms.formula(model) : '.' in formula and no 'data' argument

### ISSUE THREAD

**Issue by wbvguo** [mcol/nestfs#1]
Hi,

Thanks for maintaining this package, when I try to replace the independent variables with any other variables in the dataframe, (just like `lm` function), it shows an error

Code:
```
library(nestfs)
data(diabetes)
fs.res <- fs(Y ~ ., diabetes, family=gaussian())
```

Error:
```
Error in terms.formula(model) : '.' in formula and no 'data' argument
```

I believe the problem is that the program cannot understand the syntax correctly, is there any plan to fix it (or provide an alternative way to get around this issue)?

Thanks,

**Comment by mcol** [comment]
The formula to `fs()` should declare the baseline model from which you want the selection to start. When you write `Y ~ .` it means that you would like all the available variables in the initial model, but then you wouldn't have any variables left to select.

If you want to fit a model with all variables, then no selection can occur, so `fs()` wouldn't be the right function to call, but you should call `lm()` or `glm()` directly.

If you mean to start from a null model, that is a model that only contains an intercept, you should write `Y ~ 1`. 

I'll try to fix that error in any case to report a meaningful message.

**Comment by mcol** [comment]
I've committed 02a3a010ce0381cabe63fb5b7a43ec8bf0515769 to report a better error message in case of including all available predictors in the initial model. The updated package is already on CRAN.
